version: '3.8'

services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app-container
    volumes:
      - php-app-data:/var/www/html
    ports:
      - "8000:80"
    environment:
      - OPcache.enable=1
      - OPcache.memory_consumption=256
      - OPcache.max_accelerated_files=20000
      - OPcache.revalidate_freq=60
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: affrah
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./affrahdb.sql:/docker-entrypoint-initdb.d/affrahdb.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpassword" ]
      interval: 5s
      timeout: 10s
      retries: 5
    command: --performance-schema=ON --innodb-buffer-pool-size=1G

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    depends_on:
      - db

volumes:
  db_data:
  php-app-data: